hash-format = "sha256"

[[files]]
file = "config/EssentialCommands.properties"
hash = "5eb6c6ea5082278b578548cfc19bec62fcda4b42f312d20c27e36a2f092979c5"

[[files]]
file = "config/luckperms/luckperms.conf"
hash = "dbda616bf6b1b4f4165c19827032fb0c42ecebb9c13e6cd9d34351450a9c2c87"

[[files]]
file = "config/spawn_notification.json"
hash = "34ce09b974f3b5906e558056e6cfd8eff339f888c529e7883d17326b76f7e31e"

[[files]]
file = "config/styled-chat.json"
hash = "1985379146f31fbcbd1e9cd6d23d09cad07726d167e3fd10b4e80d99f179d3b4"

[[files]]
file = "config/styledplayerlist/config.json"
hash = "a3b66a6e204a0bed403a978b566de49d17968b7269d547b22680a8b44a7fe35b"

[[files]]
file = "config/styledplayerlist/styles/default.json"
hash = "138a2e61d6d84697df0f0a45f0eefe8556ebc0d5417cb4bb4524036a7df3f817"

[[files]]
file = "config/timeoutout.json"
hash = "8e4c10a202578f86f648649f1b9baca28eebf5a15316253867e3b27a9d7a61c3"

[[files]]
file = "config/xaero/lib/client.cfg"
hash = "43ed9dbfa5b4d6f0f3d2e8c2ced17ad298164b22c68ff11d415257a39b074336"

[[files]]
file = "config/xaero/lib/common.cfg"
hash = "98f698d96a6d21d830a455b4ad045b70516fa63c298021742d8499e7f0366cd2"

[[files]]
file = "config/xaero/lib/profiles/default.cfg"
hash = "34ae854b17d896d7cb853bdc28c27231a3947e91cb9f0991f372846ee3c2a907"

[[files]]
file = "config/xaero/lib/server_profiles/default.cfg"
hash = "d438aea41ca41e93697e059f523686935c0add482f6abe96b532bbf10c6ed80a"

[[files]]
file = "config/xaero/minimap/client.cfg"
hash = "c0915eff5d1a7905cd1038d646eb9086fd1a29e2f637d53535e4da161de17b9f"

[[files]]
file = "config/xaero/minimap/common.cfg"
hash = "2b49df024c03a369c62a303c72755e7fedeb4f4653ff53a12fd37bd83ccd4ed0"

[[files]]
file = "config/xaero/minimap/default_radar_categories_client.json"
hash = "94fc0e69a1754ef80c54e1f3c9193526c620b0ac646f94a4a0f560bcc58826a8"

[[files]]
file = "config/xaero/minimap/default_radar_categories_server.json"
hash = "a4c652cafa7dea324e5f5cf3b1df46a84e54b6d4f877195857bce55a559c1cfd"

[[files]]
file = "config/xaero/minimap/profiles/default.cfg"
hash = "22dd7f25bd75f24f54080249a7ecb52668fa62af4733a788d2ec747c7474a9d0"

[[files]]
file = "config/xaero/minimap/profiles/entity_radar_categories/default.cfg.json"
hash = "98ea0cb29739df8163c7b8fd30fa0353c44ed2602a3e24cce4d76ed3e0574417"

[[files]]
file = "config/xaero/minimap/profiles/info_display_config/default.cfg.txt"
hash = "184e654fa1fc8ad09943c97c4e65ab78acb5b3cfca22417a831513d1b6d9bbc6"

[[files]]
file = "config/xaero/minimap/server_profiles/default.cfg"
hash = "d438aea41ca41e93697e059f523686935c0add482f6abe96b532bbf10c6ed80a"

[[files]]
file = "config/xaero/world-map/client.cfg"
hash = "deece0fe0d29f2203a9699143a6209c451e91d7ecb799489c328b0d0fa31a90d"

[[files]]
file = "config/xaero/world-map/common.cfg"
hash = "0c229eb0daf85bd09af51f21eeeb99497a3bd50a825d5ab1ca695fb21bf6cf9d"

[[files]]
file = "config/xaero/world-map/profiles/default.cfg"
hash = "7b24c882801bcc7f0a8aedc625d419f661fa490fa0e9d5ebe39599a1ce2dcbd5"

[[files]]
file = "config/xaero/world-map/server_profiles/default.cfg"
hash = "d438aea41ca41e93697e059f523686935c0add482f6abe96b532bbf10c6ed80a"

[[files]]
file = "config/xaerohud.txt"
hash = "8d13c5f398016036aa4fdefb366ef3926d89f96ca104155bc9f6e5a7ec682ecd"

[[files]]
file = "datapacks/allthemons-x-mega-showdown-legacy.pw.toml"
hash = "7372dfaeadad463fe2b09274b811c26b6e6caf9ef9e7a35f634cf9fc78ccffd5"
metafile = true

[[files]]
file = "mods/accessories-compat-layer.pw.toml"
hash = "427ebc22faea5a83602994fda8ce762e45246472a5637debd5dcab22553917ce"
metafile = true

[[files]]
file = "mods/accessories.pw.toml"
hash = "5285ba249b00d0d12a3cd1f64a5536e7618770dee31d3d240f9d4345ef69f888"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "1102440dd2533ba3a154419bb95ff1f81b858201eb0c44d2a2eea486c74e565a"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
hash = "93f989575eec26f333d4253f1af961983ba4d5179e1c3237b643836b40614a43"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "a9f6cf1a98bc318c887b672aecaff6ffdbf33a6ec06af5f2686b292988d0846e"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "a4d21da45c40e8f1e3b76c9855ea3f1c15736cf2b12475e9de3efd05f8f48a8d"
metafile = true

[[files]]
file = "mods/chisel-reborn.pw.toml"
hash = "66d6af01197c4e7ac6caf7bdba1734b2e90fe8c48b842100f3d9a468722cc970"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "446c173c87b7908daee86b0dee89c6b628c77beb7a0bc091ff5252b7c0062080"
metafile = true

[[files]]
file = "mods/cobblecuisine.pw.toml"
hash = "dd9c84c3f22e37ee533990585112642b5c9a7ede61d29e5d13330a99b9a48b02"
metafile = true

[[files]]
file = "mods/cobbledollars.pw.toml"
hash = "25f8930a5814dfd54e697263a558293058e6c07603a44169b55e9fcea5ffd2e7"
metafile = true

[[files]]
file = "mods/cobblefurnies.pw.toml"
hash = "e4017e270ceacfe8dff8cdba6a657b903c002133a3bc88e8dbd54c6f55812b16"
metafile = true

[[files]]
file = "mods/cobblemon-additions.pw.toml"
hash = "ade2bd4db7d5a79135cc492d72dbe72e21af5d704dfb88e6dc7622b684da31dd"
metafile = true

[[files]]
file = "mods/cobblemon-armors.pw.toml"
hash = "c560409d67633469a0f679cf88c116c243174364bc65bb889ca4b9df9be40e88"
metafile = true

[[files]]
file = "mods/cobblemon-badgebox.pw.toml"
hash = "dbcd6c1d82ef54574a85b8aa7a74d91cfbeca90830706346d2e1ee5bf2b9c86f"
metafile = true

[[files]]
file = "mods/cobblemon-capture-xp.pw.toml"
hash = "0b1740cc342248a7bf917a147d6b8e852a9253dfbcfe180f7cf50f97bf6d646e"
metafile = true

[[files]]
file = "mods/cobblemon-cobblestats.pw.toml"
hash = "6ae09cfd9cb42c9eec7bb878c5f05fb74138f02b93363b4ec3c6817f63a17dd5"
metafile = true

[[files]]
file = "mods/cobblemon-counter.pw.toml"
hash = "215d686df072cc66bfcdee1b3543ec8ce7bc77ae4b07f53cda31c0256fdf4071"
metafile = true

[[files]]
file = "mods/cobblemon-fight-or-flight-reborn.pw.toml"
hash = "222a814ae1ace3f2324b34661c4e4dd73e59a130fee2da7c2672994e375bd6ed"
metafile = true

[[files]]
file = "mods/cobblemon-integrations.pw.toml"
hash = "ea89eb2440d0836c498a13b6e991f186f5a593329d2af127b65f113862254ff8"
metafile = true

[[files]]
file = "mods/cobblemon-mega-showdown.pw.toml"
hash = "2d0184c17562e8849657239ecb9b63f48333a2b19ca44ac5491b2fc14815ea0f"
metafile = true

[[files]]
file = "mods/cobblemon-move-inspector.pw.toml"
hash = "784184013f308a4fbec92b2ab5610969ca33ec547fd953fcc9d50cd2095d63e2"
metafile = true

[[files]]
file = "mods/cobblemon-pasture-loot.pw.toml"
hash = "253284368b80980f3261e44b2a539db0a608f525c6adfe8f096803de0c8e9c90"
metafile = true

[[files]]
file = "mods/cobblemon-pokemon-badges.pw.toml"
hash = "f9fca804b47d62948dc79c800723fa4e2e8d114171af6c19c901a59b99fbb073"
metafile = true

[[files]]
file = "mods/cobblemon-pokenav.pw.toml"
hash = "eb51c053d004eafca2bca4cb91f9fedcee372fdf78c89fbbc6914c0fd103fc99"
metafile = true

[[files]]
file = "mods/cobblemon-smartphone.pw.toml"
hash = "fa11027f3f1ffe00a9e55a1f4087d3faa6cead371e098c6b060e2be06cfeddff"
metafile = true

[[files]]
file = "mods/cobblemon-spawn-notification.pw.toml"
hash = "fcae16c281a1fce8c440f65e333fdd318a7f738dd41c9102cf76f649968d2d97"
metafile = true

[[files]]
file = "mods/cobblemon-tim-core.pw.toml"
hash = "d4209af3e46ad2c248598c3d09e00325752f05464d43a57b1178669efafb2670"
metafile = true

[[files]]
file = "mods/cobblemon-utility-ivs-evs-more-no-recipes.pw.toml"
hash = "3f598e66ddf09ec796aaa0f59085f6a95f2c794a185c91f90b8b675e19b738b9"
metafile = true

[[files]]
file = "mods/cobblemon.pw.toml"
hash = "6413f6c6bef7abc5a808a54111f093a17daf4471e89d8535840f2a24966bdcd4"
metafile = true

[[files]]
file = "mods/cobblemonrizetweaks.pw.toml"
hash = "6ae1eedd3c131b5be53fba2ae48d53a4992fe2361a574bfd07c3d2df64ba2702"
metafile = true

[[files]]
file = "mods/cobblepedia.pw.toml"
hash = "9ad38f6af18aa40e336f51314f6262cd0a8f3b6e2864f0216c5815efa71f4273"
metafile = true

[[files]]
file = "mods/cobblespawners.pw.toml"
hash = "d65c20b4b5001b05bc098736e5356939d9a035fa4414c8b5a87f28e1f80552b6"
metafile = true

[[files]]
file = "mods/cobblethemes.pw.toml"
hash = "7af8b7876f9e730eb2da137c6f2e85739dfbf69a706dca95b991c68dac3ca742"
metafile = true

[[files]]
file = "mods/cobbreeding.pw.toml"
hash = "e1f7a7bc656fb2af171219849b67b26d496881ac5a4405573a122ad344441261"
metafile = true

[[files]]
file = "mods/crafttweaker.pw.toml"
hash = "faaff57c5b26e464bebc517f3ead8df1ccc5050affa8340f309579ea0088fc15"
metafile = true

[[files]]
file = "mods/crossstitch.pw.toml"
hash = "899a506ec93d9bbc84e58aebeb369847493f97a4383e6691a5d51dbb9c2f6ea2"
metafile = true

[[files]]
file = "mods/cryonicconfig.pw.toml"
hash = "077f974ae79a14457e1a900ba42397c5d3d2896303a446b826e0b83db4c3b821"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "7cb9e98526468233fbec6f949c78a8afc5ef29447868e1d11cb71293237966a2"
metafile = true

[[files]]
file = "mods/e-utils.pw.toml"
hash = "0477f41e688eb95d6106b4df2c4fd433023d0b36d1ee6aed1a4e885cb2d26716"
metafile = true

[[files]]
file = "mods/essential-commands.pw.toml"
hash = "4f128957cb3715a76e340e35273e9b38e474a0a3798a325f1b0a998db9d5c0c1"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "49884f2d7db0e731facf0aa70cf2038dd513624c450cba773a8ca7a47e53953b"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "408151861cc1b1a4c4e9c8a3550662a2fc36d0ea96ee07b7e96c5d2a6afacf6f"
metafile = true

[[files]]
file = "mods/fabric-permissions-api.pw.toml"
hash = "4f7bf8d60ef81f12471455f634bde52cc5a8c845250845b4519ad44ea46e61a6"
metafile = true

[[files]]
file = "mods/faux-custom-entity-data.pw.toml"
hash = "5f67c621095cc9e107d2a379b3fca4bd844f51f9a8e11a560daf107bb0320f03"
metafile = true

[[files]]
file = "mods/flan.pw.toml"
hash = "1e7e4408dbd4dc1494e097721a858282f1ddb8ae48b07c414def7beb9db88510"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "238b3ceb4214a682480ce00eefae5d34efa299ff6ff667e4b2f2ed503c6e76ee"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "fe2682e6dbdd4350863e1fcd3f5f211fb437cf7791539bedd50779745beb5232"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "a104f2f6044d43bbc5a5badc6f589b2f6f5a1b9c9e47e00dfbad5061aa3b51f4"
metafile = true

[[files]]
file = "mods/hiddenmons-cobblemon.pw.toml"
hash = "d2e4214bbe6f93f7f95f688989ee296b419b7dba10dee858abb346ae73b4cfbe"
metafile = true

[[files]]
file = "mods/icommon.pw.toml"
hash = "44ecb5c09a3810f6c605f4e403e3c42c0ee40da91ccd3748d9a02fee746f6ce3"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "44f1fbc496fb2d54467ccbe0df5362c54542193e33b8541ad75b532e1baf775e"
metafile = true

[[files]]
file = "mods/invview.pw.toml"
hash = "515b020926d1fd0b6d1a32d106a376ba2c77bc5587bed99cecbc2d944ad18a99"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "37a45ed98e4edc9c8224cb06f72be8914fae69687601d4e15009f1cb9f27563c"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
hash = "6e212e9056ddaf5dda18ff6a243c118b1cf839a8ba42b999c594f85751896a33"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "76a2560989102413693bbfbea83570287b3dce4f6ed40dc69aacbd3268633fe7"
metafile = true

[[files]]
file = "mods/just-enough-resources-jer.pw.toml"
hash = "334701aa0b0a795ae1d61edb4f8a325a0439f61f298012f025480fb2bdb5e8e7"
metafile = true

[[files]]
file = "mods/luckperms-fabric-placeholders.pw.toml"
hash = "b84a80c04bff01a423b26a2fcbe6cc1efbdf3d789831a37c20df2bd56f61dd92"
metafile = true

[[files]]
file = "mods/luckperms.pw.toml"
hash = "88b5510e39cdc8ca356d54bc436edc777d5eafc03203a8724784183408fe6792"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "b9651d06e56ad51c1cdcf4b03b6a34328b7dc941f263ff92b189ee26a47cc224"
metafile = true

[[files]]
file = "mods/more-cobblemon-tweaks.pw.toml"
hash = "b008dca46f8a4241def14990a429352173cdfba8aab0fbe427b20437df54f78b"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "7fc969e77edc3b0b9946b42070fd858349a74555f0cf9648907241af8a3a2d25"
metafile = true

[[files]]
file = "mods/multiworld.pw.toml"
hash = "4d60813e8db9261205387f5c8cb96d0b372d3bbe78159369abbddab24f4b8788"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "60a3d23eb73106ecb6ba5a391d4539e3557cbd9b1f3611a2de08052155d78b3a"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "1c86eb0c48eb53d3e6aa704f7c52eb64946b488855f785ab07b0fd3112311288"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "bf0551888bcfaa93ecde7d2b3dc0ef8238e9bdec9285246c81a206c0a529b735"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "1c13286be4f09e25c93ef1640335a951df1dd0f155f6d7a173dfc284831e09c3"
metafile = true

[[files]]
file = "mods/rctapi.pw.toml"
hash = "f02ba583f7e666dae9fd2a8aa329022af65f47ed264066b3df0367ed67eed52b"
metafile = true

[[files]]
file = "mods/rctmod.pw.toml"
hash = "8a49f4c1a215d767fb6b00370fc8e294cbde06f9508f8f2196d0a8230ec544cd"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "d3f633dd12cd039a4e58dd398d1c80a324b0d78b9da5b3972b69640bfed211ed"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
hash = "7115961dc4a355e257229fdfdcef5ce8bc1003b015cfaa18e8203fd79b34a860"
metafile = true

[[files]]
file = "mods/serene-seasons.pw.toml"
hash = "4739fd0f979dd5fefecc5c47a07ef61ca78d1bdf525cd4e544e1a331ede3ca61"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "e42572fc721676972c9e562a0b1811de7bd8a646696213316f9e113de8a527a4"
metafile = true

[[files]]
file = "mods/simpletms-tms-and-trs-for-cobblemon.pw.toml"
hash = "27f2a11921312246d216d0c0c021f9c2602e5a06fb17ba6f8c12ee8542d8826a"
metafile = true

[[files]]
file = "mods/skinrestorer.pw.toml"
hash = "4edb064b4556fc614f9b921099b94e07ec10ce7bf2e5ea5ddad566acc32223ec"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks-(unoffical-fabric-port).pw.toml"
hash = "a4eebb2bda9daccc5444b8bd2d91f4ee8ce2325dd51436cb785ca33530b98ecd"
metafile = true

[[files]]
file = "mods/sophisticated-core-(unofficial-fabric-port).pw.toml"
hash = "693fdc79c18086a2a939b45de97ca918d895d5a4247d2a0bba94bf53661bc705"
metafile = true

[[files]]
file = "mods/sophisticated-storage-(unofficial-fabric-port).pw.toml"
hash = "f2feec4a404ea1ebff1cbc8ef801d074fc8c4a528af064fd9c125f5c9e57c824"
metafile = true

[[files]]
file = "mods/styled-chat.pw.toml"
hash = "81b8a1d186cc1685641bef736eadd143fa48909bd50cd7c975ec0d971a25e3ba"
metafile = true

[[files]]
file = "mods/styledplayerlist.pw.toml"
hash = "cbd24cdc5e83c7f687d56ed15b79f0e4ea890d9e825f747357e22831f67f4f0f"
metafile = true

[[files]]
file = "mods/timeoutout.pw.toml"
hash = "8eb676c3f60e847715828e28ac1dc41ee85df4dcffcad95047e8044febe18f93"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "860812150cb54f0d9ee1bce7b72798b6cc5f752bb05709f0c60231d054ec281d"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
hash = "695176ca996e639044d0d526cd6c56a95c9897e85e7a8119a2d14a712f755733"
metafile = true

[[files]]
file = "mods/wanteditems.pw.toml"
hash = "e086b63ff4f1c7aa481d4494b6cdaed3448410ef7c70f7f801edc8d4ba756240"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "e5b1fa334e6e3ebe560b1a9d7b7d6a97cc1d21bfec6ab9fb4e1b632d6fad0b68"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "08d4775f8546564ad812b09062633ffc48f44b76328efe3832c021651af86b14"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "d7c23c5b2f03df76caa7a4d66ca7961a5a3d05c538e1bda65bfd93fb80a07c5e"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "97a62d0b00bdb7f6a2ba51ad05b2ed8c3ebe06098ce893b3d638d59498addf7f"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "af20070dd9497817a83162c17b181a0a44f7213ea302d059a81c5aed02d0c877"
metafile = true

[[files]]
file = "options.txt"
hash = "1739890e01f398078819c3ed50035667581f74dcb2c4a06625f18a1536e863fb"

[[files]]
file = "resourcepacks/Cobblemon Conquest - Pokedex.zip"
hash = "b09c7135f61e1b5d4fa461416362c8071df0d0d5aff425fa6f7779331a543971"

[[files]]
file = "resourcepacks/allthemons-x-mega-showdown-legacy.pw.toml"
hash = "ae49f98d32894b377270e2a8bb13ad1fd0d48dbbfd01b847e68642af20a96630"
metafile = true

[[files]]
file = "resourcepacks/e19_cobblemon_minimap_icons.pw.toml"
hash = "224356816f38b00457a54268435fc051f03b8f649cf9df099c676e5641f9b57f"
metafile = true

[[files]]
file = "scripts/disable-shulker-boxes.zs"
hash = "7fc02f56ef0330b50e58f03b1ea044abee53706aed2d3c50f3d1ede76bd0c4bd"

[[files]]
file = "servers.dat"
hash = "68049a307efa27a19765bfeb47ed0b8629ba180e9fe0b02f390be5a373af39aa"
