name = "cobblemon-conquest"
author = "albercl"
version = "0.0.6-hf1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ecb58dfae51707d838e018ead0eff29b732c7c9d7d4fd3cea37358dc342e493"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "datapacks"
